name: timelines_upgraded
version: 0.1.0
description: A maintained fork of the 'timelines' package with updates for Dart & Flutter SDKs. Original by chulwoo-park.
homepage: https://github.com/Harish-Sunteknology/timelines_upgraded
repository: https://github.com/Harish-Sunteknology/timelines_upgraded
issue_tracker: https://github.com/Harish-Sunteknology/timelines_upgraded/issues

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter: 
